[build]
  command = "echo 'Сборка уже выполнена в CI'"
  publish = "dist/.output/public"
  functions = "dist/.netlify/functions-internal" 
  
[functions]
  directory = ".netlify/functions-internal"

[build.processing]
  skip_processing = true